In [1]:
from itertools import combinations
import numpy as np
import random
import math


In [2]:
# this is a comment
n_sets = 7
b = range(1, n_sets)

c = list(combinations(b, 2))
c

[(1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 5),
 (4, 6),
 (5, 6)]

In [3]:
list(b)

[1, 2, 3, 4, 5, 6]

In [4]:
ap = random.sample(list(range(1,16)), 4)
type(ap)


list

In [5]:
a = [2,3]
b = [1,5,3,20,2]
c = [[2,3],
    [4,5],
    [6,7]]



In [6]:
# def ismember(A,B):
#     return [np.sum(a in B) for a in A]

def ismember(A, B):
    ret_list = []
    for rows in A:
        ret_list.append([np.sum(a in B) for a in rows])

    return np.array(ret_list)

In [7]:
q = ismember(c, b)
q = q.sum(axis=1) == 1
sum(q)

1

In [8]:
p = np.zeros((3,3))
p

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:

x = np.random.randn(4,1) + 2
x.shape[0]
np.maximum(x,3)


array([[3.],
       [3.],
       [3.],
       [3.]])

In [10]:
a = np.arange(1,10)
a = a.reshape((3,3))
print(a)
b = np.array([1,1,2])

np.where(b == 1)
a[np.where(b==1),0] = 11
a

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[11,  2,  3],
       [11,  5,  6],
       [ 7,  8,  9]])

In [11]:
a = [0]*5
b = np.ones((3,3))
a.append(b)
a.append(2*b)

a[0] = b
a

[array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]), 0, 0, 0, 0, array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]), array([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])]

In [12]:
import math

def comb(n,r):
    f = math.factorial
    return int(f(n)/(f(r) * f(n-r)))

comb(15,5)



3003

In [13]:
dia = np.diag(b)
sq = np.sqrt(dia)


In [14]:
arr = np.arange(8).reshape(4,2)
arr = arr==1
np.sum(arr, 1)

array([1, 0, 0, 0])

In [15]:
t = np.array(list(range(5)))
id1 = np.nonzero(t)
sq1 = sq>1
#print(sq1)
np.logical_not(sq1)

g = [[100, 101],[200, 201]]
sq[2:4, 1:3] = g
e, ev = np.linalg.eig(sq)
np.min(e)

IndexError: too many indices for array

In [ ]:
b = np.array(b)
b.shape[1]
a1 = np.array(a)
len(a1)
a1[0].shape[0]
a1.shape[0]


In [39]:
np.append(arr, arr, axis=0)
x_aug = []
#np.append(x_aug,arr,axis=0)
x_aug.append(arr)
x_aug.append(arr)
x_aug = np.array(x_aug)
a[5]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])