In [1]:
from itertools import combinations
import numpy as np
import random
import math
import scipy as sp
import scipy.linalg as spl

In [ ]:
# this is a comment
n_sets = 7
b = range(1, n_sets)

c = list(combinations(b, 2))
c

In [ ]:
list(b)

In [ ]:
ap = random.sample(list(range(1,16)), 4)
type(ap)


In [ ]:
a = [2,3]
b = [1,5,3,20,2]
c = [[2,3],
    [4,5],
    [6,7]]



In [ ]:
# def ismember(A,B):
#     return [np.sum(a in B) for a in A]

def ismember(A, B):
    ret_list = []
    for rows in A:
        ret_list.append([np.sum(a in B) for a in rows])

    return np.array(ret_list)

In [ ]:
q = ismember(c, b)
q = q.sum(axis=1) == 1
sum(q)

In [ ]:
p = np.zeros((3,3))
p

In [ ]:

x = np.random.randn(4,1) + 2
x.shape[0]
np.maximum(x,3)


In [ ]:
a = np.arange(1,10)
a = a.reshape((3,3))
print(a)
b = np.array([1,1,2])

np.where(b == 1)
a[np.where(b==1),0] = 11
a

In [ ]:
a = [0]*5
b = np.ones((3,3))
a.append(b)
a.append(2*b)

a[0] = b
a

In [36]:
import math

def comb(n,r):
    f = math.factorial
    return int(f(n)/(f(r) * f(n-r)))

comb(5,2)



10

In [ ]:
dia = np.diag(b)
sq = np.sqrt(dia)


In [ ]:
arr = np.arange(8).reshape(4,2)
arr = arr==1
np.sum(arr, 1)

In [ ]:
t = np.array(list(range(5)))
id1 = np.nonzero(t)
sq1 = sq>1
#print(sq1)
np.logical_not(sq1)

g = [[100, 101],[200, 201]]
sq[2:4, 1:3] = g
e, ev = np.linalg.eig(sq)
np.min(e)

In [ ]:
b = np.array(b)
b.shape[1]
a1 = np.array(a)
len(a1)
a1[0].shape[0]
a1.shape[0]


In [ ]:
np.append(arr, arr, axis=0)
x_aug = []
#np.append(x_aug,arr,axis=0)
x_aug.append(arr)
x_aug.append(arr)
x_aug = np.array(x_aug)
a[5]

In [ ]:
a2 = np.array([])
b2 = np.arange(0,12).reshape((4,3))

a2 = np.append(a2, b2)
b2
l1 = []
l1.append(b2)
l1.append(b2*2)
lnp = np.array(l1)
lnp.shape
lnp[1, 0:3]

In [ ]:
l1 = np.array([1,2,23,3,4,4,55,6,6,7])
lsq = np.square(l1[:3])
lsq
np.sum(b2)

In [ ]:
def list_find(lst, val):
    """
    search for an item in a list of tuples and return it's index
    Args:
        lst (): 
        val (): 

    Returns:

    """
    idx = []
    for i in range(len(lst)):
        if val in lst[i]:
            idx.append(i)

    return idx


In [6]:
from itertools import combinations

cb = list(combinations(range(1, 5),2))

cb
1 in cb[0]
cb



[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]

In [ ]:
npa = np.tile(tot_dims, [1,n_sets])
np.append(npa, [999,34])

In [16]:
ar1 = np.array([[ 0.9186 ,   0.9104,    0.6234],
               [0.6442 ,   0.8203,    0.7156],
               [0.8199,    0.7156,    0.5701],
               [0.6939,    0.7475,    0.7206],
               [0.7890,    0.6793,    0.8181],
               [0.6328,    0.6209,    0.8490]])


ar2 = np.zeros((6,2))
ar3 = np.append(ar1, ar2, 1)
idx = np.nonzero(ar3)
ar4 = np.zeros((6,5))
ar4[idx] = 1
ar4

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [ ]:
v1 = np.append(np.tile(n_sets, [1, 3]), [2,3])
ar3[np.where(ar3 >0)] = 999
ar3

In [23]:
am1 = np.array([1,1,1,0,0,0])
am2 = np.array([0,0,1,0,0])
l = np.nonzero(am2)
int(l[0])

2

In [21]:
t1 = np.mean(ar1,1) #np.array([1,2,3,4])
np.transpose(np.tile(t1,(5,1)))

#np.array([t1]*4)

array([[0.81746667, 0.81746667, 0.81746667, 0.81746667, 0.81746667],
       [0.7267    , 0.7267    , 0.7267    , 0.7267    , 0.7267    ],
       [0.70186667, 0.70186667, 0.70186667, 0.70186667, 0.70186667],
       [0.72066667, 0.72066667, 0.72066667, 0.72066667, 0.72066667],
       [0.76213333, 0.76213333, 0.76213333, 0.76213333, 0.76213333],
       [0.7009    , 0.7009    , 0.7009    , 0.7009    , 0.7009    ]])

In [36]:
y1 = np.linspace(1,-1, 7)
x1 = np.zeros(7)
xy = map(list, zip(x1,y1))
pos = dict(zip(range(7), xy))
pos

{0: [0.0, 1.0],
 1: [0.0, 0.6666666666666667],
 2: [0.0, 0.33333333333333337],
 3: [0.0, 0.0],
 4: [0.0, -0.33333333333333326],
 5: [0.0, -0.6666666666666665],
 6: [0.0, -1.0]}

In [6]:
a =list(combinations(range(5), 2))
a = list(reversed(a))
a

[(3, 4),
 (2, 4),
 (2, 3),
 (1, 4),
 (1, 3),
 (1, 2),
 (0, 4),
 (0, 3),
 (0, 2),
 (0, 1)]

In [14]:
a = list(range(5))
a = np.array(a)
a
a.sum()
np.random.randn(5,1)
max(min(3,4), 5)

5

In [34]:
b = [True, False, True, False, False]
a[b] = 99 
((ar4 + ar4)==2).sum()

/home/praneeth/anaconda3/envs/my_env/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in long_scalars
  This is separate from the ipykernel package so we can avoid doing imports until


False

In [7]:
import random
a= np.ones(10,5)

a[:3:4 ]4*np.ones((10, 3))

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])